### PR TITLE
docs: Remove Pandoc dependency

### PR DESCRIPTION
**Pull request by xla**
As most of all inputs are valid markdown the existing checks didn't serve any real purpose, but made us depend on Pandoc. Which broke the ghcjs build.

### CODE REVIEW

**Comment by jameshaydon** [comment]
There are some problems with the multiline strings. Sometimes there is a space missing between words, and sometimes there is a (uselss?) newline and some indentation.

**Comment by jkarni** [comment]
I didn't notice any extra newlines while fixing, but I also didn't notice any in the generated ref docs. Anyhow, extra spaces should now be fixed.

**Comment by jameshaydon** [comment]
> I also didn't notice any in the generated ref docs

The reference docs go through pandoc, so newlines would be cleaned up. But actually the newlines/indentations I saw (using `(apropos!)`) are in docstrings of prelude functions. Maybe we could tweak `def` a bit to clean this up.

**Comment by jkarni** [comment]
Btw, including `reference.rst` since RTD can't build it automatically.

**Pull request merged**
