### PR TITLE
Make `cons` and `filter` work for vectors

### PR DESCRIPTION
**Pull request by geigerzaehler**

### CODE REVIEW

**Comment by jkarni** [comment]
> I'm just wondering what we should do about sequence polymorphism in general. Now we have cons and add-left which do the same thing except add-left is just for vectors. It seems a bit arbitrary.

Agreed - like Clojure's [`seq`](https://clojure.org/reference/sequences). I'd say `String` should also have `cons` and `filter`.

**Comment by geigerzaehler** [comment]
How do we proceed here? Should I make some change or should I close this PR?

**Comment by jameshaydon** [comment]
We should have `head`, `tail` and `cons` functions that work on all sequences (as this PR implements). Not sure about the names though, we might want names more like Clojure (`first`, `rest`, `cons`) to imply that it works on all sequences, not just lists.

Another thing is that whatever happens, the patterns should match the functions, that is, `/cons` in `prelude/patters.rad` should be made to work on lists and vectors if that's what `cons` does.

**Comment by geigerzaehler** [comment]
How about this: I’ll make `/cons` work with Vectors, too and add `first` and `rest` to work with both vectors and lists.

**Comment by jameshaydon** [comment]
Sounds good, and then close #196.

**Comment by geigerzaehler** [comment]
@jameshaydon: Can you have another look?

**Comment by jameshaydon** [comment]
Shall we also get rid of `add-left`?

**Comment by geigerzaehler** [comment]
> Shall we also get rid of `add-left`?

Done

**Pull request merged**
